// Code generated by protoc-gen-go. DO NOT EDIT.
// source: home.proto

package app_demopb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type HelloRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_home_992161aabd05aee7, []int{0}
}
func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (dst *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(dst, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type HelloReply struct {
	Data                 string   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloReply) Reset()         { *m = HelloReply{} }
func (m *HelloReply) String() string { return proto.CompactTextString(m) }
func (*HelloReply) ProtoMessage()    {}
func (*HelloReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_home_992161aabd05aee7, []int{1}
}
func (m *HelloReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloReply.Unmarshal(m, b)
}
func (m *HelloReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloReply.Marshal(b, m, deterministic)
}
func (dst *HelloReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloReply.Merge(dst, src)
}
func (m *HelloReply) XXX_Size() int {
	return xxx_messageInfo_HelloReply.Size(m)
}
func (m *HelloReply) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloReply.DiscardUnknown(m)
}

var xxx_messageInfo_HelloReply proto.InternalMessageInfo

func (m *HelloReply) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type HelloStreamReply struct {
	Data                 string   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloStreamReply) Reset()         { *m = HelloStreamReply{} }
func (m *HelloStreamReply) String() string { return proto.CompactTextString(m) }
func (*HelloStreamReply) ProtoMessage()    {}
func (*HelloStreamReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_home_992161aabd05aee7, []int{2}
}
func (m *HelloStreamReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloStreamReply.Unmarshal(m, b)
}
func (m *HelloStreamReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloStreamReply.Marshal(b, m, deterministic)
}
func (dst *HelloStreamReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloStreamReply.Merge(dst, src)
}
func (m *HelloStreamReply) XXX_Size() int {
	return xxx_messageInfo_HelloStreamReply.Size(m)
}
func (m *HelloStreamReply) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloStreamReply.DiscardUnknown(m)
}

var xxx_messageInfo_HelloStreamReply proto.InternalMessageInfo

func (m *HelloStreamReply) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func init() {
	proto.RegisterType((*HelloRequest)(nil), "app.demopb.HelloRequest")
	proto.RegisterType((*HelloReply)(nil), "app.demopb.HelloReply")
	proto.RegisterType((*HelloStreamReply)(nil), "app.demopb.HelloStreamReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HomeClient is the client API for Home service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HomeClient interface {
	Hello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
	HelloStream(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (Home_HelloStreamClient, error)
}

type homeClient struct {
	cc *grpc.ClientConn
}

func NewHomeClient(cc *grpc.ClientConn) HomeClient {
	return &homeClient{cc}
}

func (c *homeClient) Hello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/app.demopb.Home/Hello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *homeClient) HelloStream(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (Home_HelloStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Home_serviceDesc.Streams[0], "/app.demopb.Home/HelloStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &homeHelloStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Home_HelloStreamClient interface {
	Recv() (*HelloStreamReply, error)
	grpc.ClientStream
}

type homeHelloStreamClient struct {
	grpc.ClientStream
}

func (x *homeHelloStreamClient) Recv() (*HelloStreamReply, error) {
	m := new(HelloStreamReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// HomeServer is the server API for Home service.
type HomeServer interface {
	Hello(context.Context, *HelloRequest) (*HelloReply, error)
	HelloStream(*HelloRequest, Home_HelloStreamServer) error
}

func RegisterHomeServer(s *grpc.Server, srv HomeServer) {
	s.RegisterService(&_Home_serviceDesc, srv)
}

func _Home_Hello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HomeServer).Hello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.demopb.Home/Hello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HomeServer).Hello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Home_HelloStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(HelloRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(HomeServer).HelloStream(m, &homeHelloStreamServer{stream})
}

type Home_HelloStreamServer interface {
	Send(*HelloStreamReply) error
	grpc.ServerStream
}

type homeHelloStreamServer struct {
	grpc.ServerStream
}

func (x *homeHelloStreamServer) Send(m *HelloStreamReply) error {
	return x.ServerStream.SendMsg(m)
}

var _Home_serviceDesc = grpc.ServiceDesc{
	ServiceName: "app.demopb.Home",
	HandlerType: (*HomeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hello",
			Handler:    _Home_Hello_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "HelloStream",
			Handler:       _Home_HelloStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "home.proto",
}

func init() { proto.RegisterFile("home.proto", fileDescriptor_home_992161aabd05aee7) }

var fileDescriptor_home_992161aabd05aee7 = []byte{
	// 170 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xca, 0xc8, 0xcf, 0x4d,
	0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x4a, 0x2c, 0x28, 0xd0, 0x4b, 0x49, 0xcd, 0xcd,
	0x2f, 0x48, 0x52, 0x52, 0xe2, 0xe2, 0xf1, 0x48, 0xcd, 0xc9, 0xc9, 0x0f, 0x4a, 0x2d, 0x2c, 0x4d,
	0x2d, 0x2e, 0x11, 0x12, 0xe2, 0x62, 0xc9, 0x4b, 0xcc, 0x4d, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0,
	0x0c, 0x02, 0xb3, 0x95, 0x14, 0xb8, 0xb8, 0xa0, 0x6a, 0x0a, 0x72, 0x2a, 0x41, 0x2a, 0x52, 0x12,
	0x4b, 0x12, 0x61, 0x2a, 0x40, 0x6c, 0x25, 0x35, 0x2e, 0x01, 0xb0, 0x8a, 0xe0, 0x92, 0xa2, 0xd4,
	0xc4, 0x5c, 0x9c, 0xea, 0x8c, 0xfa, 0x18, 0xb9, 0x58, 0x3c, 0xf2, 0x73, 0x53, 0x85, 0xac, 0xb9,
	0x58, 0xc1, 0x1a, 0x84, 0x24, 0xf4, 0x10, 0x8e, 0xd1, 0x43, 0x76, 0x89, 0x94, 0x18, 0x16, 0x99,
	0x82, 0x9c, 0x4a, 0x25, 0x06, 0x21, 0x4f, 0x2e, 0x6e, 0x24, 0xdb, 0xf0, 0x18, 0x21, 0x83, 0x21,
	0x83, 0xe4, 0x40, 0x25, 0x06, 0x03, 0xc6, 0x24, 0x36, 0x70, 0x88, 0x18, 0x03, 0x02, 0x00, 0x00,
	0xff, 0xff, 0xa0, 0x33, 0x9a, 0xf8, 0x1f, 0x01, 0x00, 0x00,
}
