// Code generated by protoc-gen-go. DO NOT EDIT.
// source: home.proto

/*
Package app_homepb is a generated protocol buffer package.

It is generated from these files:
	home.proto

It has these top-level messages:
	HelloRequest
	HelloReply
*/
package app_homepb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type HelloRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *HelloRequest) Reset()                    { *m = HelloRequest{} }
func (m *HelloRequest) String() string            { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()               {}
func (*HelloRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type HelloReply struct {
	Errno  int32  `protobuf:"varint,1,opt,name=errno" json:"errno,omitempty"`
	Errmsg string `protobuf:"bytes,2,opt,name=errmsg" json:"errmsg,omitempty"`
	Data   string `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
}

func (m *HelloReply) Reset()                    { *m = HelloReply{} }
func (m *HelloReply) String() string            { return proto.CompactTextString(m) }
func (*HelloReply) ProtoMessage()               {}
func (*HelloReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *HelloReply) GetErrno() int32 {
	if m != nil {
		return m.Errno
	}
	return 0
}

func (m *HelloReply) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

func (m *HelloReply) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func init() {
	proto.RegisterType((*HelloRequest)(nil), "app.homepb.HelloRequest")
	proto.RegisterType((*HelloReply)(nil), "app.homepb.HelloReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Home service

type HomeClient interface {
	Hello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type homeClient struct {
	cc *grpc.ClientConn
}

func NewHomeClient(cc *grpc.ClientConn) HomeClient {
	return &homeClient{cc}
}

func (c *homeClient) Hello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := grpc.Invoke(ctx, "/app.homepb.Home/Hello", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Home service

type HomeServer interface {
	Hello(context.Context, *HelloRequest) (*HelloReply, error)
}

func RegisterHomeServer(s *grpc.Server, srv HomeServer) {
	s.RegisterService(&_Home_serviceDesc, srv)
}

func _Home_Hello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HomeServer).Hello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.homepb.Home/Hello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HomeServer).Hello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Home_serviceDesc = grpc.ServiceDesc{
	ServiceName: "app.homepb.Home",
	HandlerType: (*HomeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hello",
			Handler:    _Home_Hello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "home.proto",
}

func init() { proto.RegisterFile("home.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 167 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xca, 0xc8, 0xcf, 0x4d,
	0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x4a, 0x2c, 0x28, 0xd0, 0x03, 0xf1, 0x0b, 0x92,
	0x94, 0x94, 0xb8, 0x78, 0x3c, 0x52, 0x73, 0x72, 0xf2, 0x83, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b,
	0x84, 0x84, 0xb8, 0x58, 0xf2, 0x12, 0x73, 0x53, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0xc0,
	0x6c, 0x25, 0x3f, 0x2e, 0x2e, 0xa8, 0x9a, 0x82, 0x9c, 0x4a, 0x21, 0x11, 0x2e, 0xd6, 0xd4, 0xa2,
	0xa2, 0xbc, 0x7c, 0xb0, 0x12, 0xd6, 0x20, 0x08, 0x47, 0x48, 0x8c, 0x8b, 0x2d, 0xb5, 0xa8, 0x28,
	0xb7, 0x38, 0x5d, 0x82, 0x09, 0xac, 0x13, 0xca, 0x03, 0x99, 0x97, 0x92, 0x58, 0x92, 0x28, 0xc1,
	0x0c, 0x31, 0x0f, 0xc4, 0x36, 0x72, 0xe6, 0x62, 0xf1, 0xc8, 0xcf, 0x4d, 0x15, 0xb2, 0xe6, 0x62,
	0x05, 0x9b, 0x2b, 0x24, 0xa1, 0x87, 0x70, 0x91, 0x1e, 0xb2, 0x73, 0xa4, 0xc4, 0xb0, 0xc8, 0x14,
	0xe4, 0x54, 0x2a, 0x31, 0x24, 0xb1, 0x81, 0xfd, 0x62, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xfc,
	0x38, 0xa8, 0x1b, 0xd9, 0x00, 0x00, 0x00,
}
